[workspace]
resolver = "3"
members = ["crates/nounsql-core", "crates/nounsql-cli", "crates/nounsql-lsp", "crates/nounsql-site", "crates/nounsql-wasm"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/misebox/nounsql"
homepage = "https://misebox.github.io/nounsql"
authors = ["misebox"]
keywords = ["dsl", "ddl", "schema", "sql", "postgres"]
categories = ["database", "compilers", "command-line-utilities"]
rust-version = "1.91"

[workspace.dependencies]
nounsql-core = { path = "crates/nounsql-core", version = "0.1.0" }

[profile.release]
strip = true
lto = true
codegen-units = 1
